name: Swift CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    container: swift:6.1
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Print Swift version
      run: swift --version
    
    - name: Build
      run: swift build --verbose
    
    - name: Run tests
      run: swift test --disable-xctest --verbose
    
    - name: Build for release
      run: swift build -c release

