name: Swift CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Swift
      uses: swift-actions/setup-swift@v2
      with:
        swift-version: '6.1'
    
    - name: Print Swift version
      run: swift --version
    
    - name: Build
      run: swift build --verbose
    
    - name: Run tests
      run: swift test --disable-xctest --verbose
      # Note: --disable-xctest runs only Swift Testing framework
    
    - name: Build for release
      run: swift build -c release

